"""Adiciona campos de saldo e despesas informadas no usuário

Revision ID: 28397c297c20
Revises: 
Create Date: 2025-04-07 23:26:54.869576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28397c297c20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('valor',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_informado', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('despesas_informadas', sa.Float(), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('despesas_informadas')
        batch_op.drop_column('saldo_informado')

    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('valor',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
